version: '3.7'

services:

  mongo-db:
    image: mongo
    ports:

      - '27017:27017'

  server:
    build: ums-server
    image: roei_backend
    ports:
      - '3000:3000'
    links:
      - mongo-db

  client:
    build: ums-client
    image: roei_frontend
    ports:
      - '80:80'